### ISSUE TITLE
Add to @atom-haskell

### ISSUE THREAD

**Issue by moodmosaic** [moodmosaic/ide-haskell-ghcide#2]
Could this be added to @atom-haskell? It'd be great, apart from that it would enable broad(er) reach.

---

FWIW, this extension is [listed in the official ghcide `README`](https://github.com/digital-asset/ghcide/blob/master/README.md#using-with-atom).

**Comment by moodmosaic** [comment]
:crossed_fingers: /cc @lierdakil @ThomasHickman

**Comment by lierdakil** [comment]
Hi. Thanks for the ping. I've been meaning to do _something_ like this for a while, but there are a few snags here and there.

First, atom-ide-ui is good and all, but it's been discontinued by Facebook, so while it does work still, it could potentially break at any moment, and relying on it doesn't seem like a good idea in the long term.

ide-haskell does provide similar UI (although geared more towards Haskell specifically), but it uses different internal APIs, so it's not at the moment possible to use atom-languageclient-derived package with ide-haskell.

Second, atom-haskell aims to provide a more "integrated" experience, which also includes cabal/stack, repl via ghci, etc. Messages from all of these sources need to be aggregated, to avoid multiple reports for the same issue, which atom-ide-engine can't do on its own anyway. Ide-haskell does this.

So yeah. There are two ways to proceed here. I could -- at least in theory -- add atom-languageclient-compatible APIs to ide-haskell, but that would be rather limiting in places, due to some deficincies in Atom-IDE APIs. Or someone (perhaps you?) could write an ide-haskell-compatible wrapper for ghcide/hie/lsp, which would be better, but is a fair bit of work.

So the question is, what future do you envision for this project exactly?

**Comment by moodmosaic** [comment]
Thank you for your answer.

>ide-haskell does provide similar UI

Oh, this package is by no means a replacement for `ide-haskell`

> atom-ide-ui is good and all, but it's been discontinued by Facebook

At least they ought to mention it there https://atom.io/packages/atom-ide-ui but they don't :thinking:

>atom-haskell aims to provide a more "integrated" experience

:+1: I see what you mean, cool.

>[Option 1] add atom-languageclient-compatible APIs to ide-haskell

Sounds like too much work with a bit of a fragile end result (see your second option below)

>[Option 2] write an ide-haskell compatible wrapper for ghcide/hie/lsp [basically, just lsp]

That's a much better option, it's also compatible with the overall goal of LSP

---

>what future do you envision for this project exactly?

I plan to keep this package around for as long as atom-ide-ui works, with future plans to turn it into an ide-haskell compatible wrapper for ghcide/hie/lsp.

Atom's incremental parsing system via [tree-sitter](http://tree-sitter.github.io/tree-sitter/) and the preciseness of [language-haskell](https://github.com/atom-haskell/language-haskell) really keep me from moving elsewhere.

---

I think I've discussed/answered to all topics. Up to you whether you'd like to show this package in @atom-haskell. :eyes: :smiley:

**Comment by lierdakil** [comment]
> At least they ought to mention it there https://atom.io/packages/atom-ide-ui but they don't ￼

They kinda-sorta dropped the ball on that one. Facebook just suddenly stopped all work on Nuclide and related projects (including atom-ide-ui), archived those on GitHub, wrote a blog post amounting to "sorry, but that's how it is", and that was it. I'm certain there was some internal discussion, but we mere mortals only get to see the sudden end result. So yeah, not surprising they didn't update the package description. Here's Atom's blog post on the topic: https://blog.atom.io/2018/12/12/facebook-retires-nuclide-extension.html

> Sounds like too much work with a bit of a fragile end result 

Well, no, not really, to both of those. Atom-ide-ui isn't going anywhere in terms of its API on the count of being retired and archived, so the end result won't be *that* fragile. It certainly won't be optimal, but it'll work. Also, it's not *that* much work. Certainly less work than writing a complete LSP wrapper from the ground up. That said, a less arduous path to "option 2" could be forking atom-languageclient and repurposing it for ide-haskell.

**Comment by moodmosaic** [comment]
Thank you for the great discussion so far.

>forking atom-languageclient and repurposing it for ide-haskell

So instead atom-ide-ui one would use ide-haskell for the UI stuff?

**Comment by lierdakil** [comment]
> So instead atom-ide-ui one would use ide-haskell for the UI stuff?

Basically, yes. I will admit I didn't think about this too much, so there might be some gotchas there. But in theory it should be doable.
